openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development servers
  - url: https://task-api-elne.onrender.com
    description: Production server
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
  /tasks/{id}:
    $ref: paths/taskById.yaml
